/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tts.gui;

import java.awt.ComponentOrientation;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import tts.core.TTSEngine;


public class FrmCreate extends javax.swing.JPanel {
    
    TTSEngine tts = TTSEngine.getTTSEngine();

    /**
     * Creates new form FrmCreate
     */
    public FrmCreate() {
        initComponents();
        Settings.setDirection(this, ComponentOrientation.RIGHT_TO_LEFT);
        TxtPth.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblPth = new javax.swing.JLabel();
        TxtPth = new javax.swing.JTextField();
        BtnBrws = new javax.swing.JButton();
        BtnGo = new javax.swing.JButton();
        PrgWrk = new javax.swing.JProgressBar();
        ChkTrans = new javax.swing.JCheckBox();

        LblPth.setText("المسار :");

        BtnBrws.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tts/gui/icons/browse.png"))); // NOI18N
        BtnBrws.setPreferredSize(new java.awt.Dimension(35, 35));
        BtnBrws.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBrwsActionPerformed(evt);
            }
        });

        BtnGo.setText("حول");
        BtnGo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGoActionPerformed(evt);
            }
        });

        ChkTrans.setText("إنشاء ملف مقاطع Transcription (للاستخدام ضمن أداة MBROLIGN)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblPth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPth, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBrws, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PrgWrk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChkTrans)
                            .addComponent(BtnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPth)
                    .addComponent(BtnBrws, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChkTrans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrgWrk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGoActionPerformed
        PrgWrk.setIndeterminate(true);
        Thread th = new Thread(new Runnable() {
            
            @Override
            public void run() {
                if (tts.createAudio(Settings.getSettings().getMBROLA(), Settings.getSettings().getPhonemeDB(), TxtPth.getText(), ChkTrans.isSelected())) {
                    JOptionPane.showMessageDialog(FrmCreate.this, "تمت العملية بنجاح", "رسالة", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(FrmCreate.this, "حدث الخطأ التالي أثناء التوليد :\n" + tts.getError(), "خطأ", JOptionPane.ERROR_MESSAGE);
                }
                PrgWrk.setIndeterminate(false);
            }
        });
        th.start();

    }//GEN-LAST:event_BtnGoActionPerformed

    private void BtnBrwsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBrwsActionPerformed
        JDialog Mbrola_Select = new JDialog((JFrame) null, "الرجاء اختيار مسار الحفظ", true);
        
        JFileChooser choose = new JFileChooser();
        choose.setDialogTitle("الرجاء اختيار مسار الحفظ");
        choose.setFileFilter(new FileFilter() {
            
            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().toLowerCase().endsWith(".wav");
            }
            
            @Override
            public String getDescription() {
                return "WAV Audop files(*.wav)";
            }
        });
        int res = choose.showOpenDialog(Mbrola_Select);
        if (res == JFileChooser.APPROVE_OPTION) {
            String path = choose.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".wav")) {
                path = path + ".wav";
            }
            TxtPth.setText(path);
        }
    }//GEN-LAST:event_BtnBrwsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBrws;
    private javax.swing.JButton BtnGo;
    private javax.swing.JCheckBox ChkTrans;
    private javax.swing.JLabel LblPth;
    private javax.swing.JProgressBar PrgWrk;
    private javax.swing.JTextField TxtPth;
    // End of variables declaration//GEN-END:variables
}
