/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tts.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.ButtonUI;
import javax.swing.plaf.basic.BasicButtonUI;
import tts.audioplayer.AudioPlayer;
import tts.core.*;
import tts.core.phonemes.types.EndType;
import tts.core.phonemes.types.Word;

import tts.core.preprocess.vocalrules.VocalRule;

/**
 *
 * @author ossama
 */
public class FrmMain extends javax.swing.JFrame {

    TTSEngine tts;
    Settings set = Settings.getSettings();
    String AudioTarget = "";
    AudioPlayer player = new AudioPlayer();
    FrmText txt = new FrmText();
    FrmVP vp = new FrmVP();

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        vp.setVisible(false);
        initComponents();
        tts = new TTSEngine();
        View.setViewportView(txt);
        Timer t = new Timer(1, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                BtnNxt.setEnabled(!txt.getText().equals(""));
                BtnPrv.setEnabled(vp.isVisible());
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tbl = new javax.swing.JToolBar();
        BtnPrv = new javax.swing.JButton();
        BtnNxt = new javax.swing.JButton();
        View = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AraTTS");
        setMinimumSize(new java.awt.Dimension(500, 350));

        Tbl.setRollover(true);

        BtnPrv.setText("السابق");
        BtnPrv.setFocusable(false);
        BtnPrv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPrv.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnPrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrvActionPerformed(evt);
            }
        });
        Tbl.add(BtnPrv);

        BtnNxt.setText("التالي");
        BtnNxt.setFocusable(false);
        BtnNxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnNxt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnNxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNxtActionPerformed(evt);
            }
        });
        Tbl.add(BtnNxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tbl, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addComponent(View)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(View, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNxtActionPerformed
        if (txt.isVisible()) {
            String text = txt.getText();
            if (!text.equals("")) {
                Word[] words = tts.convert(text);
                if (words == null) {
                    JOptionPane.showMessageDialog(this, "حدث الخطأ التالي أثناء التحويل :\n" + tts.getError(), "خطأ", JOptionPane.ERROR_MESSAGE);
                } else {
                    vp.setWords(words);
                    txt.setVisible(false);
                    vp.setVisible(true);
                    View.setViewportView(vp);
                }

            }
        } else {
            if (!tts.createAudio(Settings.getSettings().getMBROLA(),
                    Settings.getSettings().getPhonemeDB(), "/home/ossama/Desktop/a.wav")) {
                JOptionPane.showMessageDialog(this, "حدث الخطأ التالي أثناء التوليد :\n" + tts.getError(), "خطأ", JOptionPane.ERROR_MESSAGE);

            } else {
                AudioPlayer a = new AudioPlayer();
                try {
                    a.open("/home/ossama/Desktop/a.wav");
                } catch (UnsupportedAudioFileException ex) {
                    Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                a.play();
            }
        }
    }//GEN-LAST:event_BtnNxtActionPerformed

    private void BtnPrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrvActionPerformed
        txt.setVisible(true);
        vp.setVisible(false);
        View.setViewportView(txt);
    }//GEN-LAST:event_BtnPrvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());        //</editor-fold>
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNxt;
    private javax.swing.JButton BtnPrv;
    private javax.swing.JToolBar Tbl;
    private javax.swing.JScrollPane View;
    // End of variables declaration//GEN-END:variables
}
