/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tts.gui;

import java.awt.ComponentOrientation;
import java.io.IOException;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tts.audioplayer.AudioPlayer;

public class FrmPlay extends javax.swing.JPanel {
    
    private String AudioFile = "";
    private final AudioPlayer audio;

    /**
     * Creates new form FrmPlay
     */
    public FrmPlay() {
        initComponents();
        Settings.setDirection(this, ComponentOrientation.RIGHT_TO_LEFT);
        audio = new AudioPlayer();
    }
    
    public void setFile(String file) {
        try {
            audio.open(file);
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            JOptionPane.showMessageDialog((JFrame) null, "حدث الخطأ التالي : \n" + ex.getLocalizedMessage(), "خطأ", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlTop = new javax.swing.JPanel();
        BtnPP = new javax.swing.JButton();
        BtnS = new javax.swing.JButton();
        SclBrPos = new javax.swing.JScrollBar();
        LblTotal = new javax.swing.JLabel();
        LblCurrent = new javax.swing.JLabel();

        BtnPP.setText("jButton1");
        PnlTop.add(BtnPP);

        BtnS.setText("jButton2");
        PnlTop.add(BtnS);

        SclBrPos.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        SclBrPos.setBorder(null);

        LblTotal.setText("00:00");

        LblCurrent.setText("00:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblCurrent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SclBrPos, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblTotal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(SclBrPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(LblCurrent)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPP;
    private javax.swing.JButton BtnS;
    private javax.swing.JLabel LblCurrent;
    private javax.swing.JLabel LblTotal;
    private javax.swing.JPanel PnlTop;
    private javax.swing.JScrollBar SclBrPos;
    // End of variables declaration//GEN-END:variables
}
