/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tts.gui.train;

import java.awt.ComponentOrientation;
import tts.gui.Settings;

/**
 *
 * @author Ossama Nasser <ossnass@gmail.com>
 */
public class FrmTrain extends javax.swing.JDialog {

    int index;
    FrmWrking work = new FrmWrking();
    FrmTStngs stngs = new FrmTStngs();

    /**
     * Creates new form FrmTrain
     */
    public FrmTrain(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Settings.setDirection(this, ComponentOrientation.RIGHT_TO_LEFT);
        View.setViewportView(stngs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TblBtns = new javax.swing.JToolBar();
        BtnBack = new javax.swing.JButton();
        BtnNxt = new javax.swing.JButton();
        View = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("تدريب النظام الخبير");

        TblBtns.setFloatable(false);
        TblBtns.setRollover(true);

        BtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tts/gui/icons/previous.png"))); // NOI18N
        BtnBack.setText("السابق");
        BtnBack.setFocusable(false);
        BtnBack.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        TblBtns.add(BtnBack);

        BtnNxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tts/gui/icons/next.png"))); // NOI18N
        BtnNxt.setText("التالي");
        BtnNxt.setFocusable(false);
        BtnNxt.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BtnNxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNxtActionPerformed(evt);
            }
        });
        TblBtns.add(BtnNxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TblBtns, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(View)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TblBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(View, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        switch (index) {
            case 0:
                break;
            case 1:
                View.setViewportView(stngs);
                index--;
                break;
        }
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnNxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNxtActionPerformed
        switch (index) {
            case 0:
                if (stngs.isValidValues()) {
                    work.setInitialValues(stngs.getInitialValues());
                    work.setTrainingData(stngs.getTrainingData());
                    work.setTrainingRounds(stngs.getTrainingRounds());
                    View.setViewportView(work);
                    index++;
                }
                break;
            case 1:
                break;
        }
    }

    private void BtnPrvActionPerformed(java.awt.event.ActionEvent evt) {
        switch (index) {
            case 0:
                break;
            case 1:
                View.setViewportView(stngs);
                index--;
                break;

        }
    }//GEN-LAST:event_BtnNxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnNxt;
    private javax.swing.JToolBar TblBtns;
    private javax.swing.JScrollPane View;
    // End of variables declaration//GEN-END:variables
}
