/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tts.gui.train;

import java.awt.ComponentOrientation;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import tts.core.TTSEngine;
import tts.core.expertsystem.Statistic;
import tts.core.listeners.TrainingEvent;
import tts.core.listeners.TrainingListener;
import tts.gui.Settings;

/**
 *
 * @author Ossama Nasser <ossnass@gmail.com>
 */
public class FrmWrking extends javax.swing.JPanel {

    private TTSEngine tts = TTSEngine.getTTSEngine();
    private double[][] res;
    private String TrainingData;
    private int TrainingRounds;

    public void setTrainingRounds(int TrainingRounds) {
        this.TrainingRounds = TrainingRounds;
    }

    public void setInitialValues(double[][] res) {
        this.res = res;
    }

    public void setTrainingData(String TrainingData) {
        this.TrainingData = TrainingData;
    }

    /**
     * Creates new form FrmWrking
     */
    public FrmWrking() {
        initComponents();
        Settings.setDirection(this, ComponentOrientation.RIGHT_TO_LEFT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblStsLbl = new javax.swing.JLabel();
        LblSts = new javax.swing.JLabel();
        PrgWK = new javax.swing.JProgressBar();
        BtnTrain = new javax.swing.JButton();
        BtnSve = new javax.swing.JButton();

        LblStsLbl.setLabelFor(LblSts);
        LblStsLbl.setText("الحالة :");

        BtnTrain.setText("تدريب");
        BtnTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTrainActionPerformed(evt);
            }
        });

        BtnSve.setText("حفظ النتيجة");
        BtnSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PrgWK, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblStsLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblSts))
                            .addComponent(BtnSve)
                            .addComponent(BtnTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblStsLbl)
                    .addComponent(LblSts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrgWK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnTrain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnSve)
                .addContainerGap(170, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSveActionPerformed
        JDialog Mbrola_Select = new JDialog((JFrame) null, "الرجاء اختيار مسار الحفظ", true);

        JFileChooser choose = new JFileChooser();
        choose.setDialogTitle("الرجاء اختيار مسار الحفظ");
        choose.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().toLowerCase().endsWith(".attd");
            }

            @Override
            public String getDescription() {
                return "AraTTSJ Training Data";
            }
        });
        int res_loc = choose.showSaveDialog(Mbrola_Select);
        if (res_loc == JFileChooser.APPROVE_OPTION) {
            String path = choose.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".attd")) {
                path = path + ".attd";
            }
            try {
                Statistic.saveToFile(path);
                JOptionPane.showMessageDialog(this, "تم الحفظ بنجاح", "نجاح", JOptionPane.INFORMATION_MESSAGE);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "لم تتم عملية الحفظ", "خطأ", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(FrmWrking.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtnSveActionPerformed

    private void BtnTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTrainActionPerformed
        PrgWK.setValue(0);

        new Thread(new Runnable() {

            @Override
            public void run() {
                tts.trainExpertSystem(TrainingRounds, res, TrainingData, new TrainingListener() {

                    @Override
                    public void trainingStatusChanged(TrainingEvent e) {
                        PrgWK.setValue((int) Math.round(e.getProgress()));
                        LblSts.setText(e.getProgress() + "%");
                    }
                });

                JOptionPane.showMessageDialog(FrmWrking.this, "تم التدريب بنجاح", "نجاح", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        ).start();
    }//GEN-LAST:event_BtnTrainActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSve;
    private javax.swing.JButton BtnTrain;
    private javax.swing.JLabel LblSts;
    private javax.swing.JLabel LblStsLbl;
    private javax.swing.JProgressBar PrgWK;
    // End of variables declaration//GEN-END:variables
}
